### ISSUE TITLE
Projects Checklist

### ISSUE THREAD

**Issue by taylormusolf** [taylormusolf/KickBacker#3]
# Projects
## Functionality
- [ ] Users can view a list of projects on splash page
- [ ] Users can view individual projects after clicking on them from splash page
- [ ] Smooth, bug free navigation
### Before Login
- [ ] User cannot create a project
- [ ] Users cannot edit existing projects
- [ ] Users cannot delete existing projects
### After Login
- [ ] Users can create a project
- [ ] Users can edit existing projects if they are the project's creator
- [ ] Users can delete existing projects if they are project's creator
## Style
- [ ] The site should look exactly like the actual site
- [ ] All relevant elements should have `cursor: pointer` on hover
- [ ] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [ ] Remove Redux logger and all console.log()'s from production
## Seeds
- [ ] Adequate and appropriate seeds
